logLevel: info
logType: std
serverPort: 9090
profilePath: "profilePath"
userName: "userName"

defaultBatchLimits:
  batchBlocksCountLimit: 10
  batchLenLimit: 1000
  batchSizeLimit: 100000
  batchTimeoutLimit: 300ms

defaultRobotExecOpts:
  executeTimeout: 0
  waitCommitAttempts: 1
  waitCommitAttemptTimeout: 0

robots:
  - chName: ch1
    collectorsBufSize: 1
    src:
      - chName: ch1
        initBlockNum: 111
      - chName: sch1
        initBlockNum: 222
      - chName: sch2
        initBlockNum: 444
  - chName: sch1
    collectorsBufSize: 1
    src:
      - chName: ch1
        initBlockNum: 111
      - chName: sch1
        initBlockNum: 222
      - chName: sch2
        initBlockNum: 444
  - chName: sch2
    collectorsBufSize: 1
    src:
      - chName: ch1
        initBlockNum: 111
      - chName: sch1
        initBlockNum: 222
      - chName: sch2
        initBlockNum: 444
    execOpts:
      executeTimeout: 10s
      waitCommitAttempts: 1
      waitCommitAttemptTimeout: 15s
  - chName: ch2
    collectorsBufSize: 1
    src:
      - chName: ch2
        initBlockNum: 222

txSwapPrefix: swaps
txMultiSwapPrefix: multi_swap
txPreimagePrefix: batchTransactions

cryptoSrc: local

redisStor:
  dbPrefix: robot
  addr:
    - 127.0.0.1:6379
    - 127.0.0.1:6380
  password: 12345
  withTLS: false
  rootCAs: