version: '3'
services:
  redis:
    image: redis:alpine
    container_name: robot-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    user: root
  vault:
    image: vault:latest
    container_name: robot-vault
    ports:
      - "8200:8200"
    restart: always
    environment:
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_DEV_ROOT_TOKEN_ID}
      - VAULT_DEV_LISTEN_ADDRESS=${VAULT_DEV_LISTEN_ADDRESS}
    volumes:
      - ../dev-data:/vault/dev-data
      - ./vault:/vault/script
    cap_add:
      - IPC_LOCK
    command: /bin/sh -c "sleep 2 && ./vault/script/init.sh & vault server -dev"