name: Go

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
  release:
    types:
      - created

jobs:
  validate:
    uses: atomyze-foundation/workflows/.github/workflows/validate--v1.yml@main

  go-qa-l0:
    needs:
      - validate
    uses: atomyze-foundation/workflows/.github/workflows/go-validate--v1.yml@main
    secrets: inherit

  docker-lint:
    needs:
      - validate
    uses: atomyze-foundation/workflows/.github/workflows/docker-lint--v1.yml@main

  go-qa-l1:
    needs:
      - go-qa-l0
      - docker-lint
    uses: atomyze-foundation/workflows/.github/workflows/go-lint--v1.yml@main

  go-qa-l2:
    needs:
      - go-qa-l1
    uses: atomyze-foundation/workflows/.github/workflows/go-test--v1.yml@main
    secrets: inherit

  go-qa-l3:
    needs:
      - go-qa-l2
    uses: atomyze-foundation/workflows/.github/workflows/go-static--v1.yml@main
    secrets: inherit

  docker-build-and-push:
    uses: atomyze-foundation/workflows/.github/workflows/docker-build-and-push--v1.yml@main
    needs:
      - go-qa-l3
    secrets: inherit
